apiVersion: v1
name: fluent-bit-out-hsdp
description: Fast and lightweight log processor and forwarder or Linux, OSX and BSD family operating systems.
keywords:
  - logging
  - fluent-bit
  - fluentd
  - hsdp
version: 0.0.9
appVersion: 1.9.2.2
icon: https://fluentbit.io/assets/img/logo1-default.png
home: https://fluentbit.io/
sources:
  - https://github.com/philips-software/fluent-bit-out-hsdp/
maintainers:
  - name: loafoe
    email: andy.loafoe@gmail.com
